[project]
name = "coding-agent"
version = "0.1.0"
description = "A simple coding agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.60.0",
    "black>=25.1.0",
    "python-dotenv>=1.1.1",
]
